### ISSUE TITLE
Resources not found 

### ISSUE THREAD

**Issue by ljaniszewski** [tingyik90/snackprogressbar#10]
when trying to display snackbar i get 
`android.content.res.Resources$NotFoundException: Resource ID #0x7f060027 type #0x2 is not valid`

creation of snack manager 
` progressSnackProgressBarManager = SnackProgressBarManager(study_code_root_view)`

calling for snack
`override fun showLoadingProgressSnackbar() {
        progressSnackProgressBarManager.show(
            SnackProgressBar(SnackProgressBar.TYPE_INDETERMINATE, "Connecting..."),
            SnackProgressBarManager.LENGTH_INDEFINITE
        )
    }`

Res ID mentioned in exception is actually ColorAccent, which is defined.
rootView in this case is ConstraintLayout

**Comment by tingyik90** [comment]
Sorry for my late reply, I was away for work. It is working fine on my phone.
Are you using the latest gradle build? Also, what API you are writing for?
Try cleaning your project and try again.

**Comment by ljaniszewski** [comment]
I am using gradle-4.4, build tools 27.0.3
 minSdkVersion 21
 targetSdkVersion 27

Cleaning didn't help. 

I tried to set progressbar color manually for the manager because it obviously has a problem with colorAccent, but no luck.

I must be doing something wrong or something is wrong :) 

Please help because I can't use android snackbar because it lacks programatically dismiss functionality.
Thanks

**Comment by ljaniszewski** [comment]
maybe it doesn't work with Kotlin? 

EDIT:
Looked through your code and it is in fact written in Kotlin.

Also found out that you're directly taking colors from user defined colors.xml, which in my case doesn't contain colorAccent, but color accent is defined in styles in main app theme like so 
`<item name="colorAccent">@color/color_darkish_purple</item>`

I added colorAccent to colors.xml and it works. 

I think you should try to use `R.attr.colorAccent` instead, but don't know if it would work

**Comment by tingyik90** [comment]
Hi, thanks for finding out the solution! I just began finding out the issue and you've already solved it.

Yes, I am taking the colorAccent from ``color.xml`` which is a common practise. As of current, there seems to be no reliable way to get the color from theme.

https://stackoverflow.com/questions/28121068/how-to-refer-to-app-theme-attributes-from-within-a-library-project
