### ISSUE TITLE
Snackbar queue doesn't work on any device except Huaweii P8

### ISSUE THREAD

**Issue by ljaniszewski** [tingyik90/snackprogressbar#12]
Displaying snackbars one after another works fine only on Huaweii p8 with android 6.0.

 I tried following use cases

1st case
1. show snackbar TYPE_INDETERMINATE (INDEFINITE)  when performing an action. On success, I call manager.dismiss or dismissAll
2. On error, I call show snackbar TYPE_MESSAGE (LENGTH_LONG) 

2nd case
1. show snackbar TYPE_INDETERMINATE (LENGTH_LONG)  when performing an action.
2. On error, I call show snackbar TYPE_MESSAGE (LENGTH_LONG) in hope that after 1 disappears this one will show up because it's queued.

both approaches work on said phone, but don't work on Samsung S4 Android 5.1, LG g3 A5.0 and LG Nexus 5x A8.1 and Nexus 5 A6.01

**Comment by tingyik90** [comment]
What do you mean by "response is error"? Can you please provide a simple code to replicate the use case? This is working fine on my Huawei P10 A8.0 and Nexus 5 A4.4.

**Comment by ljaniszewski** [comment]
API response is 403 because I deliberately give wrong credentials :)

**Comment by tingyik90** [comment]
I edited your original post to be clear. But isn't the 2nd case same as the 1st?

**Comment by tingyik90** [comment]
I edited your original post to make it more general. Can you

1. show the relevant sample code?
2. show the stack trace for error?

My advice is that when you want to show a new snackprogressbar which is important, try calling ``dismissAll()`` first before showing the new one, since any snackprogressbar that is called before is no longer relevant.

**Comment by tingyik90** [comment]
Also, try compiling using ``compile 'com.github.tingyik90:snackprogressbar:master-SNAPSHOT'`` and see if it works. I've upgraded to the latest support library, gradle and kotlin version.

**Comment by ljaniszewski** [comment]
Thanks for all help, I've made isolated use case that didn't depend on Rx chains and it turns out it appears RxJava was acting up, which affected these devices. Sorry for taking your time. The snackbars looks very well. Thanks
