### ISSUE TITLE
Align SnackProgressBar to top of layout

### ISSUE THREAD

**Issue by findyourexit** [tingyik90/snackprogressbar#19]
I've had a look around but can't seem to see if it's at all possible to use this library to create top-aligned snackbars? I absolutely love the implementation and aesthetic, but require the snackbar to align with the bottom of the system status bar, rather than the base of the screen. Apologies if I've missed something obvious here!

**Comment by ERM-MY-Devs** [comment]
Hi @findyourexit, as per Material Design, the snackbar is supposed to be shown at the bottom. This library is extending from `BaseTransientBottomBar` of Android which by default animates in and out.

I am exposing the view of SnackProgressBar `onLayoutInflated` in v6.0. However, as shown in https://stackoverflow.com/a/31746370/3584439, the default animation will make it look very ugly. You might want to consider using another library in that SO thread.

**Comment by tingyik90** [comment]
Hi @findyourexit, as per Material Design, the snackbar is supposed to be shown at the bottom. This library is extending from BaseTransientBottomBar of Android which by default animates in and out.

I am exposing the view of SnackProgressBar onLayoutInflated in v6.0. However, as shown in https://stackoverflow.com/a/31746370/3584439, the default animation will make it look very ugly. You might want to consider using another library in that SO thread.

**Comment by findyourexit** [comment]
Understood @tingyik90, I really appreciate your response.
