### ISSUE TITLE
UI blocks on using indeterminate type snackprogressbar

### ISSUE THREAD

**Issue by H-arshit** [tingyik90/snackprogressbar#2]

**Comment by tingyik90** [comment]
Please provide more information regarding this issue.

**Comment by H-arshit** [comment]
I made two buttons one to show and other to dismiss the snackbar
Once the snackbar is displayed(indeterminate type)  the ui becomes inaccessible i.e i could not press the buttons

**Comment by tingyik90** [comment]
By default, the snackprogressbar is designed to block the UI. Logically, when you have something progressing in background, the snackprogressbar should be dismissed by the app itself once the operation is finished, not by the user. Anyway, you can always allow user input by creating the snackprogressbar with

```
= new SnackProgressBar(SnackProgressBar.TYPE_INDETERMINATE, "TYPE_INDETERMINATE.")
    .setAllowUserInput(true)
```

There are other options too. Please read the javadoc. https://tingyik90.github.io/snackprogressbar/javadoc/
