### ISSUE TITLE
can't access SnackProgressBar.TYPE_HORIZONTAL 

### ISSUE THREAD

**Issue by bartekpacia** [tingyik90/snackprogressbar#20]
as the title says

After updating to v6.0, I can't set

`SnackProgressBarManager.LENGTH_INDEFINITE`
and 

`SnackProgressBar.TYPE_HORIZONTAL `

Also, there's a lot of compile-time errors. IMHO, v6.0 isn't stable

**Comment by ERM-MY-Devs** [comment]
Yes, you are right. It is working fine on my local library i.e. if you clone this repo and run DemoActivity. But when compiler by Jitpack, things just gone haywire, maybe due to the new R8 shrinker. Please don't use v6.0 for now.

Will be good if anyone can help to check my grade files to use the correct settings.

**Comment by tingyik90** [comment]
Yes, you are right. It is working fine on my local library i.e. if you clone this repo and run DemoActivity. But when compiler by Jitpack, things just gone haywire, maybe due to the new R8 shrinker. Please don't use v6.0 for now.

Will be good if anyone can help to check my grade files to use the correct settings.

**Comment by bartekpacia** [comment]
I guess you could use something like  
`ignore class` in the proguard file to avoid class the members being shrinked by PeoGuard/R8.

**Comment by tingyik90** [comment]
If you look at the top of the class, I've added `@Keep` annotations there, which previous gradle was working fine. I can roll back to the older grade version, but I'd like to get this solved properly if possible with R8.

**Comment by tingyik90** [comment]
@bartekpacia, fixed in v6.1. Please give it a try and hope you enjoy the new features. :-)

**Comment by bartekpacia** [comment]
@tingyik90 Thank you for fast reaction, preventing memory leaks by using Arch Components is always a big + 
I think it still requires adding the keep rules, because disabling shrinking is a temporary solution

**Comment by tingyik90** [comment]
`@Keep` annotations is applied to all classes, but I'm not sure whether it works. Hope that you can let me know after you try it in your app (both debug and release variant), then I can close this. Thanks!

**Comment by bartekpacia** [comment]
@tingyik90 According to my (little) knowledge in the 'shrinking field/area', you need to add `@Keep` not only to classes, but also to methods (not sure about class fields)

**Comment by tingyik90** [comment]
I have limited knowledge about Proguard as well. It is always very confusing to me, so I just leave it default. But as I know `@Keep` annotation at class level keep the whole class as it is. See quote below from [here](https://developer.android.com/studio/build/shrink-code.html#keep-code).

> Alternatively, you can add the @Keep annotation to the code you want to keep. Adding @Keep on a class keeps the entire class as-is. Adding it on a method or field will keep the method/field (and its name) as well as the class name intact.

**Comment by bartekpacia** [comment]
`SnackProgressBarManager.LENGTH_INDEFINITE` and `SnackProgressBar.TYPE_HORIZONTAL` are in a companion object, it might matter because companions are references in Java like this
`SnackProgressBar.Companion.TYPE_HORIZONTAL`

**Comment by tingyik90** [comment]
Ah... you are right. I'll add a `@Keep` annotation in the next release for `companion object`. For now, if there is no issue, I'll keep it as it is due to time constraint. I'm already squeezing out all my time. Haha.

**Comment by bartekpacia** [comment]
Take your time, you've already done a piece of awesome work, v5.0 works well
