### ISSUE TITLE
Introduce Semantic Versioning

### ISSUE THREAD

**Issue by bartekpacia** [tingyik90/snackprogressbar#21]
The library is great, but I think it'd further benefit from the introduction of [Semantic Versioning](https://semver.org/). As of now, it's kinda difficult to get an idea of versions.

**Comment by tingyik90** [comment]
I intended to follow the semantic versioning since v2.0. I guess since there is no breaking change this time, I should've released it as 5.2. Previous releases all correctly follow the rules, since they all have breaking changes. I'll keep this in mind next time. Thanks!
