### ISSUE TITLE
setProgressMax() and setMessage() not applied dynamically?

### ISSUE THREAD

**Issue by yhs0602** [tingyik90/snackprogressbar#29]
It seems that `SnackProgressBar.setProgressMax()` does not update its progress max, when it is already shown by `SnackProgressBarManager.show()`.

**Comment by yhs0602** [comment]
Maybe the internal method `SnackProgressBarCore.updateTo()` should be called when needed.

**Comment by yhs0602** [comment]
As a workaround, I shall fix the progress max to 100 and calculate progress myself.

Like [this codes](https://github.com/KYHSGeekCode/DereInfo/blob/4f9d7b4e60f90432bf2f6ef4f729aaeda977b476/app/src/main/java/com/kyhsgeekcode/dereinfo/SongListActivity.kt#L68)

**Comment by yhs0602** [comment]
And does `setMessage `.

**Comment by tingyik90** [comment]
Hi, please refer the README section for how to [UPDATE](https://github.com/tingyik90/snackprogressbar#update). Note that `SnackProgressBar` is just a container on the presentation of the bar. Once you feed into `SnackProgressBarManager.show()`, it will be **copied** into the `SnackProgressBarManager` and the `SnackProgressBar` object itself is no longer relevant. Please try and if working, close this issue. Thank you.

**Comment by yhs0602** [comment]
Yeah, it works perfectly now, thanks!
