### ISSUE TITLE
setSwipeToDismiss and setAction not applying dynamically

### ISSUE THREAD

**Issue by Andrey-Morenkov** [tingyik90/snackprogressbar#30]
I trying to implement this behaviour: show "File saving" message on snackbar and Indeterminate progress line. In that time on background file saving and when saved - i need to have possibility dismiss by swipe this message or add button "open File folder". But this not working:

` SnackProgressBar(SnackProgressBar.TYPE_HORIZONTAL, "Saving file...")`
                    `.setIsIndeterminate(true)`
                    `.setSwipeToDismiss(false)`

......

`val currentShowing = snackProgressBarManager.getLastShown()`
`currentShowing?.setMessage("File saved")`
`?.setIsIndeterminate(false)`
`?.setSwipeToDismiss(true)`
`?.setProgressMax(1)`
`?.setAction("Open folder", object: SnackProgressBar.OnActionClickListener {`
`override fun onActionClick()`
`{`
`val savingDir: File by inject(named("journalDirectory"))`
`val intent = Intent(Intent.ACTION_VIEW).setDataAndType(Uri.parse(savingDir.absolutePath), "resource/folder")`
`startActivity(intent)`
`snackProgressBarManager.dismissAll()`
`}`
`})`
` currentShowing?.also {`
`runOnUiThread {`
`snackProgressBarManager.updateTo(it)`
`snackProgressBarManager.setProgress(1)`
`}`
`}`

I.e action button not appears and swipe to dismiss still unavailable

**Comment by tingyik90** [comment]
I have tested and the action button does appear, but swipe to dismiss was unavailable. Are you using CoordinatorLayout?

**Comment by tingyik90** [comment]
@Andrey-Morenkov I have resolved this issue. Please give `'com.github.tingyik90:snackprogressbar:1efad63355'` a try. Hope that you can reply within a few days so that I can know if it solved your problem and issue as a new release.
