### ISSUE TITLE
SnackProgressBar half width on tablet

### ISSUE THREAD

**Issue by 0x7e57** [tingyik90/snackprogressbar#31]
Hello!
Is it possible to make it occupy all available space by default?
At the moment, I do it like this.

In onLayoutInflated:
`ViewGroup viewParent = (ViewGroup)snackProgressBarLayout.getParent();
CoordinatorLayout.LayoutParams params = (CoordinatorLayout.LayoutParams) viewParent.getLayoutParams();
params.width = CoordinatorLayout.LayoutParams.MATCH_PARENT;
viewParent.setLayoutParams(params);`

**Comment by tingyik90** [comment]
Yes, you are right. This is where you should make change to the layout. Did you successfully make change?

**Comment by tingyik90** [comment]
Also, if you read Material Design, the Snackbar should not fill the whole width for a widescreen.

**Comment by 0x7e57** [comment]
Yes, I made the changes successfully.
Yes, I know that the Material Design recommendations include filling the Snackbar not to its full width.

However, this library changes the snackbar logic by adding OverlayLayout and ProgressBar.
SnackProgressBar makes it possible to block user input and with this, its incomplete (not full width) representation looks strange.
This is just my opinion. Thanks.

**Comment by tingyik90** [comment]
Ah... I see what you mean. Anyway, is the OverlayLayout fully covering the screen? I know I can't satisfy everyone, which is why I exposed the layout via `onLayoutInflated` so that anyone can make the changes they preferred. If there is no bug, then I will close this issue.

**Comment by 0x7e57** [comment]
Yes, thank you!
