### ISSUE TITLE
OnActionClickListener is not safe

### ISSUE THREAD

**Issue by 0x7e57** [tingyik90/snackprogressbar#33]
Click on the ActionButton will execute the onActionClick() method and automatically close the SnackProgressBar, however, there is an opportunity (accidentally or intentionally) to click on it several times before the SnackProgressBar closes. The onActionClick() will execute twice, leading to unpredictable results.
Please lock the ActionButton after the first click.

**Comment by tingyik90** [comment]
Seems to be a valid concern, although this has been an issue in Android for a [long time](https://stackoverflow.com/questions/5608720/android-preventing-double-click-on-a-button/9950832#comment13900011_5608757).
I have made the commit 6f54f367641ca301254633d703388530eda00311 to prevent double click. Please try `implementation 'com.github.tingyik90:snackprogressbar:master-SNAPSHOT'` and let me know if this solves the issue.

**Comment by 0x7e57** [comment]
This problem occurs everywhere: when you click on View, when navigating through Fragments and Activitys and other actions in the UI.
Activity.finish()
Activity.startActivity()
navController.navigate()
...
We can not guarantee that the user does not have time to perform any other action on the still available MyViews, before one of these commands is executed. What all this can lead you can imagine. It is a pain.
Even your parentView.addView(overlayLayout) does not add overlayLayout to the screen instantly. MyViews will be available for a while.

As for the commit 6f54f36, I checked it in work, everything is fine. Thanks!

**Comment by tingyik90** [comment]
You are right and that was what led to the development of this library in the first place. 

In the early days, as I recalled, Material Design stated that user input should never be blocked even if something is in progress, which is just impossible sometimes. As we cannot predict what user will be doing over the few seconds of the process in background, the simplest method is just to block the whole screen and show a progress bar to notify user that something is happening.

Anyway, thanks for the confirmation. Releasing as [v6.4.2](https://github.com/tingyik90/snackprogressbar/releases/tag/6.4.2).

If you can offer better, faster way to add the overlayLayout, feel free to submit a pull request. Currently, when `show()` is being called, the `overlayLayout` is the first to be shown or hidden, before showing the `snackProgressBar`.
