### ISSUE TITLE
how to change background for different snackbar

### ISSUE THREAD

**Issue by LuiguiBalarezo** [tingyik90/snackprogressbar#35]
Hello how are you ?.

How could I change the background for different types of messages, such as error, success, info, warning, etc ...?

Gracias.

**Comment by tingyik90** [comment]
Unfortunately, this library is built with a single background color only, as per Material UI. You can change the background color via `snackProgressBarManager.setBackgroundColor()`.

As it is impossible to meet everyone's requirement, I've exposed the snackbar layout directly. You are always free to modify the layout as you like via `OnDisplayListener` and grab the layout in `onLayoutInflated`. See the README.
