### ISSUE TITLE
Issue with setProgress in AsyncTask

### ISSUE THREAD

**Issue by blessedvictim** [tingyik90/snackprogressbar#5]
With that code i have my work done successfully but snackbar stuck on 0% and dont dismiss
```
@Override
        protected void onPreExecute(){
            snackProgressBarManager.show(determinateType, SnackProgressBarManager.LENGTH_INDEFINITE);
        }
        @Override
        protected Void doInBackground(Void... voids) {
                //some work
                i++;
                musicFile.setAlbum(album);
                musicFile.setArtist(artist);
                musicFile.setRealPath(data);
                musicFile.setTitle(title);
                musicFile.progress= i/count * 100;//there is double and progress really changed in any iterations
                publishProgress(musicFile);

            }

            cursor.close();
            return null;
        }

        @Override
        protected void onProgressUpdate(MusicFile... progress) {
            snackProgressBarManager.setProgress((int) progress[0].progress);
        }

        @Override
        protected void onPostExecute(Void aVoid) {
            super.onPostExecute(aVoid);
            snackProgressBarManager.dismissAll();
        }
```
And with that code all work fine !!!
```
@Override
        protected void onPreExecute(){
            snackProgressBarManager.show(determinateType, SnackProgressBarManager.LENGTH_INDEFINITE);
        }

        @Override
        protected Void doInBackground(Void... voids) {
                //some work
                i++;
                musicFile.setAlbum(album);
                musicFile.setArtist(artist);
                musicFile.setRealPath(data);
                musicFile.setTitle(title);

                musicFile.progress= i/count * 100;//there is double and progress really changed in any iterations
try {
                    Thread.sleep(1);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                publishProgress(musicFile);

            }

            cursor.close();
            return null;
        }

        @Override
        protected void onProgressUpdate(MusicFile... progress) {
            snackProgressBarManager.setProgress((int) progress[0].progress);
        }

        @Override
        protected void onPostExecute(Void aVoid) {
            super.onPostExecute(aVoid);
            snackProgressBarManager.dismissAll();
        }
```
i just add sleep for 1 ms and it's worked! i think that is bug , if i wront pls tell me

**Comment by tingyik90** [comment]
Instead of passing the `musicFile` as progress, try passing directly `i` into the progress. I think as you read and write to `musicFile` at the same time, there is concurrent error. Also, there is no need to perform the % calculation. It is already built-in. Use this.

```
@Override
protected void onPreExecute(){
    determinateType.setProgressMax(count);
    snackProgressBarManager.show(determinateType, SnackProgressBarManager.LENGTH_INDEFINITE);
}

@Override
protected Void doInBackground(Void... voids) {
    // other codes here
    musicFile.progress= i/count * 100;
    publishProgress(i);
}

@Override
protected void onProgressUpdate(Integer... progress) {
    snackProgressBarManager.setProgress(progress[0]);
}
```

**Comment by blessedvictim** [comment]
ok, I did as you said
`@Override
        protected void onProgressUpdate(Integer... progress) {
            snackProgressBarManager.setProgress(progress[0]);
        }`

and now i see as SnackBarProgress stuck on 0% and onPostExecute it dismiss!
all work nice but percentage not change

**Comment by tingyik90** [comment]
It is very possible that your `doInBackground` task are completed within a few milliseconds. The updates are too fast that the progressBar is unable to respond. In this case, the `Thread.sleep()` provides the time required for UI updates. You should check your log and see how long does the whole operation takes. If it takes only a few millis, it does not make sense to update using a determinate type progress bar. This is a fundamental question on your UI design. It might be better to use indeterminate progress bar.

**Comment by blessedvictim** [comment]
maybe problem in version of my newer kotlin runtime version?

**Comment by tingyik90** [comment]
No, I don't think so. I am replicating your code in my own app and the snackProgressBar is stuck at 0% as well, if I'm updating the UI too fast.

As mentioned, how long does each loop of `doInBackground` needs? If you are updating the UI a few times every 1 ms, then the UI may not respond. UI seems to update correctly if the interval is more than 1 ms.

You can do a simple experiment. Put a ProgressBar in your layout. Update that ProgressBar instead of snackProgressBar. Check if the progressBar is updating, without the `sleep()`.

**Comment by blessedvictim** [comment]
Ok.i i will try simple progressBar
doInBackground update UI very fast, it is true , but my for loop in doInBackground may contain from 10 to about thousand iteration!!! and i want find simple way to make progressbar
thx you

**Comment by tingyik90** [comment]
Is your problem solved? I'm closing this soon.
