### ISSUE TITLE
Option to set Percentage ot timer any other text 

### ISSUE THREAD

**Issue by LOG-TAG** [tingyik90/snackprogressbar#6]
I want to use it for auto SMS OTP detect timer !!  I want custom timer limit with skip button to manually enter OTP or skip the OTP login page !! we want timer based Progressbar with time minute: seconds format! (enhancement)

**Comment by tingyik90** [comment]
You can implement you own timer to update the SnackProgressBar message e.g "Time remaining = 04:01" with the skip button.

A sample will be:

    SnackProgressBar actionType = new SnackProgressBar(SnackProgressBar.TYPE_ACTION, "Time remaining = 10s")
                .setAction("SKIP", new SnackProgressBar.OnActionClickListener() {
                    @Override
                    public void onActionClick() {
                        // do something
                    }
                })

    snackProgressBarManager.show(actionType, SnackProgressBarManager.LENGTH_INDEFINITE);

    int time = 10;

    new CountDownTimer(10000, 1000) {
        @Override
        public void onTick(long millisUntilFinished) {

            time = time - 1
            // get the currently showing snackProgressBar and change the message
            SnackProgressBar snackProgressBar = snackProgressBarManager.getLastShown();
            if (snackProgressBar != null) {
                snackProgressBar.setMessage("Time remaining = " + time + "s");
                // calling updateTo() will not hide and show again the SnackProgressBar
                snackProgressBarManager.updateTo(snackProgressBar);
            }
        }
        
        @Override
        public void onFinish() {
            snackProgressBarManager.dismiss();
        }
    }.start();
