### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by nandanugg** [tingyik90/snackprogressbar#7]
`Error:java.lang.IllegalStateException: Unexpected inputs: ImmutableJarInput{name=com.android.support:support-fragment:26.1.0, file=D:\Work\App\SiMontokKebersihanNew\app\build\intermediates\transforms\profilers-transform\debug\29.jar, contentTypes=CLASSES, scopes=EXTERNAL_LIBRARIES, status=REMOVED}, ImmutableJarInput{name=com.android.support:support-core-utils:26.1.0, file=D:\Work\App\SiMontokKebersihanNew\app\build\intermediates\transforms\profilers-transform\debug\30.jar, contentTypes=CLASSES, scopes=EXTERNAL_LIBRARIES, status=REMOVED}, ImmutableJarInput{name=com.android.support:recyclerview-v7:26.1.0, file=D:\Work\App\SiMontokKebersihanNew\app\build\intermediates\transforms\profilers-transform\debug\27.jar, contentTypes=CLASSES, scopes=EXTERNAL_LIBRARIES, status=REMOVED}, ImmutableJarInput{name=com.android.support:support-v4:26.1.0, file=D:\Work\App\SiMontokKebersihanNew\app\build\intermediates\transforms\profilers-transform\debug\13.jar, contentTypes=CLASSES, scopes=EXTERNAL_LIBRARIES, status=REMOVED}, ImmutableJarInput{name=android.arch.lifecycle:runtime:1.0.0, file=D:\Work\App\SiMontokKebersihanNew\app\build\intermediates\transforms\profilers-transform\debug\37.jar, contentTypes=CLASSES, scopes=EXTERNAL_LIBRARIES, status=REMOVED}, ImmutableJarInput{name=com.android.support:design:26.1.0, file=D:\Work\App\SiMontokKebersihanNew\app\build\intermediates\transforms\profilers-transform\debug\9.jar, contentTypes=CLASSES, scopes=EXTERNAL_LIBRARIES, status=REMOVED}, ImmutableJarInput{name=com.android.support:animated-vector-drawable:26.1.0, file=D:\Work\App\SiMontokKebersihanNew\app\build\intermediates\transforms\profilers-transform\debug\14.jar, contentTypes=CLASSES, scopes=EXTERNAL_LIBRARIES, status=REMOVED}, ImmutableJarInput{name=com.android.support:support-core-ui:26.1.0, file=D:\Work\App\SiMontokKebersihanNew\app\build\intermediates\transforms\profilers-transform\debug\31.jar, contentTypes=CLASSES, scopes=EXTERNAL_LIBRARIES, status=REMOVED}, ImmutableJarInput{name=com.android.support:transition:26.1.0, file=D:\Work\App\SiMontokKebersihanNew\app\build\intermediates\transforms\profilers-transform\debug\12.jar, contentTypes=CLASSES, scopes=EXTERNAL_LIBRARIES, status=REMOVED}, ImmutableJarInput{name=android.arch.lifecycle:common:1.0.0, file=D:\Work\App\SiMontokKebersihanNew\app\build\intermediates\transforms\profilers-transform\debug\39.jar, contentTypes=CLASSES, scopes=EXTERNAL_LIBRARIES, status=REMOVED}, ImmutableJarInput{name=com.android.support:support-media-compat:26.1.0, file=D:\Work\App\SiMontokKebersihanNew\app\build\intermediates\transforms\profilers-transform\debug\28.jar, contentTypes=CLASSES, scopes=EXTERNAL_LIBRARIES, status=REMOVED}, ImmutableJarInput{name=com.android.support:appcompat-v7:26.1.0, file=D:\Work\App\SiMontokKebersihanNew\app\build\intermediates\transforms\profilers-transform\debug\10.jar, contentTypes=CLASSES, scopes=EXTERNAL_LIBRARIES, status=REMOVED}, ImmutableJarInput{name=com.android.support:support-vector-drawable:26.1.0, file=D:\Work\App\SiMontokKebersihanNew\app\build\intermediates\transforms\profilers-transform\debug\15.jar, contentTypes=CLASSES, scopes=EXTERNAL_LIBRARIES, status=REMOVED}, ImmutableJarInput{name=com.android.support:support-compat:26.1.0, file=D:\Work\App\SiMontokKebersihanNew\app\build\intermediates\transforms\profilers-transform\debug\32.jar, contentTypes=CLASSES, scopes=EXTERNAL_LIBRARIES, status=REMOVED}`

please note that I'm using 
` androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1', {
        exclude group: 'com.google.code.findbugs'
    }`
too

**Comment by tingyik90** [comment]
SnackProgressBar is only using `'com.android.support:design:27.0.2'`.
The issue does not seem to originate from this library. Please check again.
