### ISSUE TITLE
Progress Text Color

### ISSUE THREAD

**Issue by waltertomiati** [tingyik90/snackprogressbar#8]
Hi,
the progress text color is always white (on right). I have already set all the settings like this but only text progress remains white.

snackprogressbarmanager = new SnackProgressBarManager(findViewById(R.id.layout))
                        .setProgressBarColor(R.color.colorAccent)
                        .setBackgroundColor(R.color.colorBackground)
                        .setMessageTextColor(R.color.text_color_primary)
                        .setActionTextColor(R.color.colorAccent);

colorAccent #547bd3
colorBackground #1c2029
text_color_primary #f5f5f5

**Comment by tingyik90** [comment]
Thanks for the bug report. Added `setProgressTextColor` method in v3.4.
