### ISSUE TITLE
Know if a snackbar is currently beeing shown ?

### ISSUE THREAD

**Issue by salfai** [tingyik90/snackprogressbar#9]
Hi,
Is it possible to have an option to knew if a snackbar is currently being shown?
For example : `snackProgressBarManager.isShown()` (true/false)

Thank you !

**Comment by tingyik90** [comment]
Hi, sorry for late reply as I was away for work. You can use 

    private var isShown = false;

    snackProgressBarManager = new SnackProgressBarManager(view).setOnDisplayListener(new SnackProgressBarManager.OnDisplayListener() {
        @Override
        public void onShown(int onDisplayId) {
            isShown = true    
        }

        @Override
        public void onDismissed(int onDisplayId) {
            isShown = false    
        }
    });
